import React, { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import {
  Trophy,
  Users,
  User,
  Plus,
  QrCode,
  ArrowRight,
  Clock,
  Award,
  Flame,
  CheckCircle2
} from 'lucide-react';
import { Card } from '../common/Card';
import { Button } from '../common/Button';
import { Badge } from '../common/Badge';
import { Input, Select } from '../common/Input';
import { Modal } from '../common/Modal';

export const StudentRoom: React.FC = () => {
  const { showToast } = useApp();

  const [activeTab, setActiveTab] = useState<'lobby' | 'live' | 'results'>('lobby');
  const [roomMode, setRoomMode] = useState<'single' | 'group'>('single');
  const [roomCodeInput, setRoomCodeInput] = useState('');
  const [createdRoomCode, setCreatedRoomCode] = useState('8429');

  // Live game state
  const [questionIdx, setQuestionIdx] = useState(0);
  const [score, setScore] = useState(0);
  const [streak, setStreak] = useState(0);
  const [timer, setTimer] = useState(15);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);

  const roomQuestions = [
    {
      q: 'Which Python built-in function returns both index and value when iterating?',
      options: ['zip()', 'enumerate()', 'map()', 'filter()'],
      ans: 'enumerate()'
    },
    {
      q: 'What is the average time complexity of Python dict key lookups?',
      options: ['O(1)', 'O(log N)', 'O(N)', 'O(N²)'],
      ans: 'O(1)'
    },
    {
      q: 'Which keyword creates an anonymous inline lambda function?',
      options: ['def', 'func', 'lambda', 'inline'],
      ans: 'lambda'
    }
  ];

  const currentQ = roomQuestions[questionIdx];

  // Peer participants leaderboard
  const [leaderboard, setLeaderboard] = useState([
    { name: 'Sarah Jenkins (You)', score: 0, streak: 0, avatar: 'SJ' },
    { name: 'Ahmed Tariq', score: 920, streak: 3, avatar: 'AT' },
    { name: 'Ali Raza', score: 870, streak: 2, avatar: 'AR' },
    { name: 'Zainab Fatima', score: 810, streak: 1, avatar: 'ZF' }
  ]);

  // Live round countdown
  useEffect(() => {
    if (activeTab !== 'live') return;
    const interval = setInterval(() => {
      setTimer(prev => {
        if (prev <= 1) {
          handleAdvanceQuestion();
          return 15;
        }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(interval);
  }, [activeTab, questionIdx]);

  const handleAdvanceQuestion = () => {
    if (questionIdx < roomQuestions.length - 1) {
      setQuestionIdx(prev => prev + 1);
      setSelectedOption(null);
      setTimer(15);
    } else {
      setActiveTab('results');
    }
  };

  const handleAnswer = (opt: string) => {
    setSelectedOption(opt);
    if (opt === currentQ.ans) {
      const addedPoints = 300 + timer * 10;
      setScore(prev => prev + addedPoints);
      setStreak(prev => prev + 1);
      setLeaderboard(prev =>
        prev.map(p => (p.name.includes('(You)') ? { ...p, score: p.score + addedPoints, streak: p.streak + 1 } : p))
          .sort((a, b) => b.score - a.score)
      );
    } else {
      setStreak(0);
    }
    setTimeout(() => {
      handleAdvanceQuestion();
    }, 900);
  };

  const handleStartGame = () => {
    setActiveTab('live');
    setQuestionIdx(0);
    setScore(0);
    setStreak(0);
    setTimer(15);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', maxWidth: '960px', margin: '0 auto' }}>
      {/* 1. LOBBY VIEW: JOIN OR CREATE ROOM */}
      {activeTab === 'lobby' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Trophy size={24} color="var(--color-primary-emerald)" />
              <h1 className="text-h1">Peer Competition Room</h1>
            </div>
            <p className="text-body">
              Challenge classmates to real-time multiplayer academic battles. Choose single competition or group battle.
            </p>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
            {/* Join Room */}
            <Card>
              <h3 className="text-h3" style={{ marginBottom: '14px' }}>Join an Existing Room</h3>
              <p style={{ fontSize: '13px', color: 'var(--color-text-muted)', marginBottom: '16px' }}>
                Enter the 4-digit code generated by a peer host to enter the multiplayer lobby.
              </p>

              <div style={{ display: 'flex', gap: '8px', marginBottom: '14px' }}>
                <input
                  className="input-field"
                  placeholder="Enter 4-digit code (e.g. 8429)"
                  value={roomCodeInput}
                  onChange={e => setRoomCodeInput(e.target.value)}
                  style={{ fontSize: '16px', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase' }}
                />
              </div>

              <Button variant="primary" style={{ width: '100%' }} onClick={handleStartGame}>
                Join Room Arena
              </Button>
            </Card>

            {/* Create Room */}
            <Card>
              <h3 className="text-h3" style={{ marginBottom: '14px' }}>Create Competition Room</h3>
              <div style={{ display: 'flex', gap: '10px', marginBottom: '16px' }}>
                <button
                  onClick={() => setRoomMode('single')}
                  style={{
                    flex: 1,
                    padding: '12px',
                    borderRadius: 'var(--radius-md)',
                    border: roomMode === 'single' ? '2px solid var(--color-primary-emerald)' : '1px solid var(--color-border)',
                    backgroundColor: roomMode === 'single' ? 'var(--color-mint-bg)' : '#FFFFFF',
                    cursor: 'pointer',
                    fontWeight: 600,
                    fontSize: '13px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px'
                  }}
                >
                  <User size={15} color="var(--color-primary-emerald)" /> Single 1v1
                </button>

                <button
                  onClick={() => setRoomMode('group')}
                  style={{
                    flex: 1,
                    padding: '12px',
                    borderRadius: 'var(--radius-md)',
                    border: roomMode === 'group' ? '2px solid var(--color-primary-emerald)' : '1px solid var(--color-border)',
                    backgroundColor: roomMode === 'group' ? 'var(--color-mint-bg)' : '#FFFFFF',
                    cursor: 'pointer',
                    fontWeight: 600,
                    fontSize: '13px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px'
                  }}
                >
                  <Users size={15} color="var(--color-primary-emerald)" /> Group Battle
                </button>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', backgroundColor: '#FAFAF9', borderRadius: 'var(--radius-md)', marginBottom: '16px' }}>
                <span style={{ fontSize: '13px', color: 'var(--color-text-muted)' }}>Assigned Room Code:</span>
                <span style={{ fontSize: '20px', fontWeight: 800, letterSpacing: '0.1em', color: 'var(--color-primary-emerald)' }}>
                  {createdRoomCode}
                </span>
              </div>

              <Button variant="primary" style={{ width: '100%' }} onClick={handleStartGame}>
                Launch Room & Start Battle
              </Button>
            </Card>
          </div>
        </div>
      )}

      {/* 2. LIVE COMPETITION SESSION */}
      {activeTab === 'live' && currentQ && (
        <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: '24px' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {/* Round Bar */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Badge variant="emerald">
                Question {questionIdx + 1} of {roomQuestions.length}
              </Badge>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                {streak > 1 && (
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', fontSize: '13px', fontWeight: 700, color: 'var(--color-warning)' }}>
                    <Flame size={16} /> {streak}x Streak!
                  </span>
                )}
                <div style={{ fontSize: '20px', fontWeight: 800, color: timer <= 5 ? 'var(--color-error)' : 'var(--color-primary-emerald)' }}>
                  00:{String(timer).padStart(2, '0')}
                </div>
              </div>
            </div>

            <Card style={{ padding: '28px' }}>
              <h2 className="text-h2" style={{ fontSize: '20px', lineHeight: 1.4, marginBottom: '24px' }}>
                {currentQ.q}
              </h2>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {currentQ.options.map((opt, i) => {
                  const isSelected = selectedOption === opt;
                  return (
                    <div
                      key={i}
                      onClick={() => !selectedOption && handleAnswer(opt)}
                      style={{
                        padding: '14px 18px',
                        borderRadius: 'var(--radius-md)',
                        border: isSelected ? '2px solid var(--color-primary-emerald)' : '1px solid var(--color-border)',
                        backgroundColor: isSelected ? 'var(--color-mint-bg)' : '#FFFFFF',
                        cursor: selectedOption ? 'default' : 'pointer',
                        fontSize: '14.5px',
                        fontWeight: 600,
                        color: isSelected ? 'var(--color-primary-emerald)' : 'var(--color-text-main)',
                        transition: 'all 0.15s ease'
                      }}
                    >
                      {opt}
                    </div>
                  );
                })}
              </div>
            </Card>
          </div>

          {/* Real-time Live Room Leaderboard */}
          <Card>
            <h3 className="text-h3" style={{ marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Trophy size={16} color="var(--color-primary-emerald)" />
              Live Room Standings
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {leaderboard.map((player, idx) => (
                <div
                  key={idx}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    padding: '10px 12px',
                    borderRadius: 'var(--radius-md)',
                    backgroundColor: player.name.includes('(You)') ? 'var(--color-mint-bg)' : '#FAFAF9',
                    border: player.name.includes('(You)') ? '1px solid var(--color-mint-border)' : '1px solid var(--color-border-light)'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <span style={{ fontSize: '13px', fontWeight: 700, width: '18px' }}>
                      {idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : `${idx + 1}.`}
                    </span>
                    <span style={{ fontSize: '13.5px', fontWeight: player.name.includes('(You)') ? 700 : 500 }}>
                      {player.name}
                    </span>
                  </div>
                  <span style={{ fontSize: '14px', fontWeight: 700, color: 'var(--color-primary-emerald)' }}>
                    {player.score} pts
                  </span>
                </div>
              ))}
            </div>
          </Card>
        </div>
      )}

      {/* 3. FINAL RESULTS */}
      {activeTab === 'results' && (
        <Card style={{ textAlign: 'center', padding: '40px 24px' }}>
          <div style={{ width: '64px', height: '64px', borderRadius: '50%', backgroundColor: 'var(--color-mint-bg)', color: 'var(--color-primary-emerald)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginBottom: '16px' }}>
            <Award size={32} />
          </div>
          <h2 className="text-h2" style={{ fontSize: '26px' }}>Match Finished!</h2>
          <p className="text-body" style={{ marginTop: '4px' }}>
            Final score: <strong>{score} points</strong>
          </p>

          <div style={{ display: 'flex', justifyContent: 'center', gap: '12px', marginTop: '24px' }}>
            <Button variant="secondary" onClick={() => setActiveTab('lobby')}>
              Back to Room Lobby
            </Button>
            <Button variant="primary" onClick={handleStartGame}>
              Play Again
            </Button>
          </div>
        </Card>
      )}
    </div>
  );
};
